#!/bin/bash -e

source ${STI_SCRIPTS_PATH}/assemble

chmod –R 755 /opt/app-root/src/bin
chmod –R 755 /opt/app-root/src/cgi-bin
chmod –R 777 /opt/app-root/src/daten
chmod –R 777 /mnt
chmod –R 777 /opt/rh/httpd24/root/etc/httpd/conf
chmod –R 777 /opt/rh/httpd24/root/etc/httpd/conf/httpd.conf