#!/bin/bash -e

source ${STI_SCRIPTS_PATH}/assemble

chmod –R 755 /opt/app-root/src/bin
chmod –R 777 /opt/app-root/src/daten/abbrev.txt

#post-install operations 
/usr/bin/ln -s /data/conf /opt/app-root/src/conf 
/usr/bin/ln -s /data /opt/app-root/src/daten2/daten2
